[package]
name = "ControllerServer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.5"
actix-server = "2.0"
actix-service = "2.0"
tokio = { version = "1", features = ["full"] }